service: javalibs-layer
provider:
  name: aws
  stage: ${opt:stage, 'dev'}
layers:
  javalibs:
    path: ../serverless/target/layer
    name: ${self:provider.stage}-javalibs
    description: Java libs for lambda
    compatibleRuntimes:
      - java8
    allowedAccounts:
      - '*'
    retain: false # optional, false by default. If true, layer versions are not deleted as new ones are created
resources:
  Outputs:
    JavalibsLambdaLayerExport:
      Value:
        Ref: JavalibsLambdaLayer
      Export:
        Name: JavalibsLambdaLayer